### ISSUE TITLE
UserRecordController

### ISSUE THREAD

**Issue by leshaze** [leshaze/recordsArchive#15]
**Description**
Implement new UserRecordController and userrecord table to reduce redundant items in records table.
Link records with a user and define record specific details in this table.

**ToDo**
- [ ] Create new UserRecordController
- [ ] Create new UserRecord table
- [ ] Remove duplicated items from records table
- [ ] Delete unnecessary columns from records table
- [ ] Update store records method
- [ ] Create new userrecord view
